### ISSUE TITLE
Finding rebased commits

### ISSUE THREAD

**Issue by Netel-pleb** [bactensor/github-family-observer#4]
define correct logic to find rebased commits

**Comment by nesta-onur111** [comment]
after rebase branch, commit sha is changed.
even we can find updated commits at a certain branch but it's difficult to identify which commits are newly submitted and which commits are rebased from other branch

**Comment by przadka** [comment]
just for context, right now we have duplicates to wrongly implemented rebase handling:

![image](https://github.com/user-attachments/assets/fd7746fb-d1fd-4e1b-bcb2-59d611b02bbc)
